[versions]
com-alpsbte-alpslib-alpslib-io = "1.2.0" # https://mvn.alps-bte.com/service/rest/repository/browse/alps-bte/com/alpsbte/alpslib/alpslib-io/
com-alpsbte-alpslib-alpslib-utils = "1.3.5" # https://mvn.alps-bte.com/service/rest/repository/browse/alps-bte/com/alpsbte/alpslib/alpslib-utils/
com-alpsbte-canvas = "1.3" # https://mvn.alps-bte.com/service/rest/repository/browse/alps-bte/com/alpsbte/canvas/
com-arcaniax-headdatabase-api = "1.3.2" # https://github.com/Arcaniax-Development/HeadDatabase-API/releases
com-squareup-okhttp3-okhttp-jvm = "5.3.2" # https://central.sonatype.com/artifact/com.squareup.okhttp3/okhttp-jvm
com-zaxxer-hikaricp = "7.0.2" # https://github.com/brettwooldridge/HikariCP/tags
io-papermc-paper-paper-api = "1.21.11-R0.1-SNAPSHOT"
org-jetbrains-annotations = "26.0.2" # https://central.sonatype.com/artifact/org.jetbrains/annotations
org-mariadb-jdbc-mariadb-java-client = "3.5.7" # https://central.sonatype.com/artifact/org.mariadb.jdbc/mariadb-java-client
com-gradleup-shadow = "9.3.1" # https://github.com/GradleUp/shadow/releases
com-palantir-git-version = "4.3.0" # https://github.com/palantir/gradle-git-version/releases
io-freefair-lombok = "9.2.0" # https://plugins.gradle.org/plugin/io.freefair.lombok
com-intellectualsites-bom-bom-newest = "1.55" # Ref: https://github.com/IntellectualSites/bom
com-googlecode-json-simple = "1.1.1" # https://mvnrepository.com/artifact/com.googlecode.json-simple/json-simple

[libraries]
com-alpsbte-alpslib-alpslib-io = { module = "com.alpsbte.alpslib:alpslib-io", version.ref = "com-alpsbte-alpslib-alpslib-io" }
com-alpsbte-alpslib-alpslib-utils = { module = "com.alpsbte.alpslib:alpslib-utils", version.ref = "com-alpsbte-alpslib-alpslib-utils" }
com-alpsbte-canvas = { module = "com.alpsbte:canvas", version.ref = "com-alpsbte-canvas" }
com-arcaniax-headdatabase-api = { module = "com.arcaniax:HeadDatabase-API", version.ref = "com-arcaniax-headdatabase-api" }
com-squareup-okhttp3-okhttp-jvm = { module = "com.squareup.okhttp3:okhttp-jvm", version.ref = "com-squareup-okhttp3-okhttp-jvm" }
com-zaxxer-hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "com-zaxxer-hikaricp" }
io-papermc-paper-paper-api = { module = "io.papermc.paper:paper-api", version.ref = "io-papermc-paper-paper-api" }
org-jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "org-jetbrains-annotations" }
org-mariadb-jdbc-mariadb-java-client = { module = "org.mariadb.jdbc:mariadb-java-client", version.ref = "org-mariadb-jdbc-mariadb-java-client" }
com-intellectualsites-bom-bom-newest = { module = "com.intellectualsites.bom:bom-newest", version.ref = "com-intellectualsites-bom-bom-newest" }
com-googlecode-json-simple = { module = "com.googlecode.json-simple:json-simple", version.ref = "com-googlecode-json-simple" }

[plugins]
git-version = { id = "com.palantir.git-version", version.ref = "com-palantir-git-version" }
shadow = { id = "com.gradleup.shadow", version.ref = "com-gradleup-shadow" }
lombok = { id = "io.freefair.lombok", version.ref = "io-freefair-lombok" }
